spring:
  application:
    name: building-maintenance-backend

# Common config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: 94fd467d998a5d8846585b32d170a4cbc6eaeaf62497730f96110c7ddb3166c3527ebafe
    expiration-ms: 360000000
    header: Authorization
    prefix: Bearer
  sudo:
    username: a@a.com
    password: 123456

server:
  servlet:
    context-path: /api


management:
  server:
    base-path: /
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
      discovery:
        enabled: false

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html